import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import { NavBar } from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Scott Lucas | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
